steps:
- id: 'Update Application in the VM'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh afya365-api-server --zone=us-central1-a --command='/bin/sh /home/mevis/pull.sh'